"""baseline - all existing tables

Revision ID: 75ff8d5af5a7
Revises: 
Create Date: 2026-09-18 11:45:13.650929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ff8d5af5a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('inst_id', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'inactive', name='userstatus'), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('inst_id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_inst_id'), 'admins', ['inst_id'], unique=True)
    op.create_table('attendance_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('changed_by', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=True),
    sa.Column('old_notes', sa.String(length=300), nullable=True),
    sa.Column('new_notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_audit_log_created_at'), 'attendance_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_attendance_audit_log_id'), 'attendance_audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_audit_log_session_id'), 'attendance_audit_log', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_audit_log_student_id'), 'attendance_audit_log', ['student_id'], unique=False)
    op.create_table('attendance_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_flags_created_at'), 'attendance_flags', ['created_at'], unique=False)
    op.create_index(op.f('ix_attendance_flags_id'), 'attendance_flags', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_flags_session_id'), 'attendance_flags', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_flags_student_id'), 'attendance_flags', ['student_id'], unique=False)
    op.create_table('courses',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('branch', sa.String(length=150), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('course_type', sa.String(length=100), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code')
    )
    op.create_table('device_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.String(length=50), nullable=True),
    sa.Column('lng', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_checkins_created_at'), 'device_checkins', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_checkins_device_id'), 'device_checkins', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_checkins_id'), 'device_checkins', ['id'], unique=False)
    op.create_index(op.f('ix_device_checkins_session_id'), 'device_checkins', ['session_id'], unique=False)
    op.create_index(op.f('ix_device_checkins_student_id'), 'device_checkins', ['student_id'], unique=False)
    op.create_table('faculty',
    sa.Column('inst_id', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'inactive', name='userstatus'), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('branch', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('inst_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_faculty_email'), 'faculty', ['email'], unique=True)
    op.create_index(op.f('ix_faculty_inst_id'), 'faculty', ['inst_id'], unique=True)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=150), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_created_at'), 'login_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_id'), 'login_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_login_attempts_identifier'), 'login_attempts', ['identifier'], unique=False)
    op.create_table('students',
    sa.Column('inst_id', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'inactive', name='userstatus'), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('branch', sa.String(length=150), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('course', sa.String(length=100), nullable=True),
    sa.Column('sub_section', sa.String(length=20), nullable=True),
    sa.Column('face_registered', sa.Boolean(), nullable=True),
    sa.Column('face_embedding', sa.Text(), nullable=True),
    sa.Column('face_image_b64', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('inst_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_inst_id'), 'students', ['inst_id'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gps_range', sa.Integer(), nullable=True),
    sa.Column('face_required', sa.Boolean(), nullable=True),
    sa.Column('qr_expiry', sa.Integer(), nullable=True),
    sa.Column('inst_name', sa.String(length=200), nullable=True),
    sa.Column('manual_edit_window', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=False),
    sa.Column('to_date', sa.DateTime(), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('review_note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.inst_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    op.create_index(op.f('ix_leave_requests_student_id'), 'leave_requests', ['student_id'], unique=False)
    op.create_table('timetable_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=20), nullable=False),
    sa.Column('faculty_id', sa.String(length=50), nullable=True),
    sa.Column('day_of_week', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', name='dayofweek'), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=150), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('sub_section', sa.String(length=20), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('course_type', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.code'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.inst_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_slots_id'), 'timetable_slots', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=20), nullable=False),
    sa.Column('faculty_id', sa.String(length=50), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('qr_token', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('branch', sa.String(length=150), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('sub_section', sa.String(length=20), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('course_type', sa.String(length=100), nullable=True),
    sa.Column('gps_lat', sa.String(length=50), nullable=True),
    sa.Column('gps_lng', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'active', 'closed', name='sessionstatus'), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('grace_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.code'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.inst_id'], ),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetable_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('method', sa.Enum('qr', 'qr_gps_face', 'manual', name='attendancemethod'), nullable=True),
    sa.Column('status', sa.Enum('present', 'absent', 'late', name='attendancestatus'), nullable=True),
    sa.Column('marked_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('student_lat', sa.String(length=50), nullable=True),
    sa.Column('student_lng', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.inst_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_session_student')
    )
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_timetable_slots_id'), table_name='timetable_slots')
    op.drop_table('timetable_slots')
    op.drop_index(op.f('ix_leave_requests_student_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_students_inst_id'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_login_attempts_identifier'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_created_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_faculty_inst_id'), table_name='faculty')
    op.drop_index(op.f('ix_faculty_email'), table_name='faculty')
    op.drop_table('faculty')
    op.drop_index(op.f('ix_device_checkins_student_id'), table_name='device_checkins')
    op.drop_index(op.f('ix_device_checkins_session_id'), table_name='device_checkins')
    op.drop_index(op.f('ix_device_checkins_id'), table_name='device_checkins')
    op.drop_index(op.f('ix_device_checkins_device_id'), table_name='device_checkins')
    op.drop_index(op.f('ix_device_checkins_created_at'), table_name='device_checkins')
    op.drop_table('device_checkins')
    op.drop_table('courses')
    op.drop_index(op.f('ix_attendance_flags_student_id'), table_name='attendance_flags')
    op.drop_index(op.f('ix_attendance_flags_session_id'), table_name='attendance_flags')
    op.drop_index(op.f('ix_attendance_flags_id'), table_name='attendance_flags')
    op.drop_index(op.f('ix_attendance_flags_created_at'), table_name='attendance_flags')
    op.drop_table('attendance_flags')
    op.drop_index(op.f('ix_attendance_audit_log_student_id'), table_name='attendance_audit_log')
    op.drop_index(op.f('ix_attendance_audit_log_session_id'), table_name='attendance_audit_log')
    op.drop_index(op.f('ix_attendance_audit_log_id'), table_name='attendance_audit_log')
    op.drop_index(op.f('ix_attendance_audit_log_created_at'), table_name='attendance_audit_log')
    op.drop_table('attendance_audit_log')
    op.drop_index(op.f('ix_admins_inst_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
