"""faculty leave, substitute assignments, push subscriptions, auto-notify toggle

Revision ID: c6cc080506aa
Revises: 75ff8d5af5a7
Create Date: 2026-09-19 18:45:54.292897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6cc080506aa'
down_revision: Union[str, None] = '75ff8d5af5a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('keys_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('substitute_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_request_id', sa.Integer(), nullable=False),
    sa.Column('timetable_slot_id', sa.Integer(), nullable=False),
    sa.Column('class_date', sa.DateTime(), nullable=False),
    sa.Column('original_faculty_id', sa.String(length=50), nullable=False),
    sa.Column('substitute_faculty_id', sa.String(length=50), nullable=False),
    sa.Column('course_id', sa.String(length=20), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leave_request_id'], ['leave_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_substitute_assignments_class_date'), 'substitute_assignments', ['class_date'], unique=False)
    op.create_index(op.f('ix_substitute_assignments_id'), 'substitute_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_substitute_assignments_leave_request_id'), 'substitute_assignments', ['leave_request_id'], unique=False)
    op.create_index(op.f('ix_substitute_assignments_original_faculty_id'), 'substitute_assignments', ['original_faculty_id'], unique=False)
    op.create_index(op.f('ix_substitute_assignments_substitute_faculty_id'), 'substitute_assignments', ['substitute_faculty_id'], unique=False)
    op.add_column('leave_requests', sa.Column('faculty_id', sa.String(length=50), nullable=True))
    # NOTE: wrapped in batch mode rather than a bare op.alter_column().
    # SQLite has no ALTER COLUMN at all (Alembic's plain alter_column
    # generates syntax that only works on Postgres) — batch mode handles
    # both dialects correctly, which is also what let this migration
    # actually be verified end-to-end against a real SQLite DB here
    # rather than just trusted to work on Postgres.
    with op.batch_alter_table('leave_requests') as batch_op:
        batch_op.alter_column('student_id', existing_type=sa.VARCHAR(length=50), nullable=True)
        batch_op.create_index(op.f('ix_leave_requests_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_foreign_key('fk_leave_requests_faculty_id', 'faculty', ['faculty_id'], ['inst_id'])
    op.add_column('system_settings', sa.Column('auto_notify_on_go_live', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'auto_notify_on_go_live')
    with op.batch_alter_table('leave_requests') as batch_op:
        batch_op.drop_constraint('fk_leave_requests_faculty_id', type_='foreignkey')
        batch_op.drop_index(op.f('ix_leave_requests_faculty_id'))
        batch_op.alter_column('student_id', existing_type=sa.VARCHAR(length=50), nullable=False)
        batch_op.drop_column('faculty_id')
    op.drop_index(op.f('ix_substitute_assignments_substitute_faculty_id'), table_name='substitute_assignments')
    op.drop_index(op.f('ix_substitute_assignments_original_faculty_id'), table_name='substitute_assignments')
    op.drop_index(op.f('ix_substitute_assignments_leave_request_id'), table_name='substitute_assignments')
    op.drop_index(op.f('ix_substitute_assignments_id'), table_name='substitute_assignments')
    op.drop_index(op.f('ix_substitute_assignments_class_date'), table_name='substitute_assignments')
    op.drop_table('substitute_assignments')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
